plugins {
    id 'org.springframework.boot' version '3.5.5'
    id 'java'
}

ext {
    keithVersion = '4.0.0'
    jacksonVersion = "2.17.2"
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'org.springframework.boot'

    repositories {
        mavenCentral()
    }

    compileJava.options.encoding = 'UTF-8'

    configurations.configureEach {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }

    dependencies {
        //spring
        implementation "org.springframework.boot:spring-boot-starter"
        //spring cache support
        implementation "org.springframework.boot:spring-boot-starter-cache:3.3.2"
        //additional cache support such as caffeine cache
        implementation "org.springframework:spring-context-support:6.1.14"

        //replace logback with log4j2
        implementation "org.springframework.boot:spring-boot-starter-log4j2"

        //jackson
        implementation "com.fasterxml.jackson.core:jackson-databind:$jacksonVersion"

        //database
        implementation "org.mariadb.jdbc:mariadb-java-client:3.4.1"

        testImplementation "org.junit.jupiter:junit-jupiter-engine:5.11.2"
    }

    test {
        useJUnitPlatform()
    }
}

