plugins {
    id 'application'
}

application {
    mainClassName = 'com.naeayedea.keith.core.Launcher'
}

group = 'com.naeayedea.keith.core'
version = '4.0.0-alpha'

dependencies {
    implementation project(':common')

    implementation "org.springframework.boot:spring-boot-starter-web"
}


bootJar {
    archiveBaseName = 'keith-core'
    archiveVersion = ''
}
