keith.commands.ping.internal-name=ping
keith.commands.ping.name-key=translation.i18n.commands.ping.name
keith.commands.ping.alias-key=translation.i18n.commands.ping.aliases

keith.commands.help.internal-name=help
keith.commands.help.name-key=translation.i18n.commands.help.name
keith.commands.help.alias-key=translation.i18n.commands.help.aliases

keith.commands.pin.internal-name=pin
keith.commands.pin.name-key=translation.i18n.commands.pin.name
keith.commands.pin.alias-key=translation.i18n.commands.pin.aliases

keith.commands.guess.internal-name=guess
keith.commands.guess.name-key=translation.i18n.commands.guess.name
keith.commands.guess.alias-key=translation.i18n.commands.guess.aliases

keith.commands.chat.internal-name=chat
keith.commands.chat.name-key=translation.i18n.commands.chat.name
keith.commands.chat.alias-key=translation.i18n.commands.chat.aliases
