#####################################
# SPRING BOOT
#####################################

logging.config=classpath:log4j2.xml

server.port=${SERVER_PORT}

########################
# Cloud Config
########################

spring.cloud.config.enabled=false

########################
# ACTUATOR
########################

management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true
########################
# CACHE
########################

#how often the cache fully evicts
keith.manager.cache.refresh=300

########################
# I18N
########################

spring.messages.basename=config.i18n.messages
spring.messages.fallback-to-system-locale=true

########################
# SSL
########################

## The format used for the truststore. It could be set to JKS in case it is a JKS file
#server.ssl.trust-store-type=PKCS12
## The path to the keystore containing the certificate
#server.ssl.trust-store=classpath:ssl/keystore/mytruststore.p12
## The password used to generate the certificate (recommend ciphering, but can be plain text).
#server.ssl.trust-store-password={cipher}abcdefg12345678

## The format used for the keystore. It could be set to JKS in case it is a JKS file
#server.ssl.key-store-type=PKCS12
## The path to the keystore containing the certificate
#server.ssl.key-store=classpath:ssl/keystore/mykeystore.p12
## The password used to generate the certificate (recommend ciphering, but can be plain text).
#server.ssl.key-store-password={cipher}abcdefg12345678

#####################################
# KEITH
#####################################

keith.version=[version]
keith.project.name=[projectName]
keith.default-prefix=?

########################
# DATABASE
########################

keith.database.url=jdbc:mariadb://${keith.database.dns-name}:${keith.database.port:3306}/keith?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
keith.database.user=keith
#keith.database.password=

#minimum database schema version (inclusive)
keith.database.schema.minimum-version=4.0.0
#maximum database schema version (exclusive - defaults to minimum
#keith.database.schema.maximum-version=5.0.0

#
## SQL statements
#
keith.commands.remind.statements.getReminders=SELECT GuildID, ChannelID, UserID, Date, Text FROM reminders WHERE date < ?
keith.commands.remind.statements.removeReminder=DELETE FROM reminders WHERE (GuildID \= ? AND ChannelID \= ? AND UserID \= ? AND Date \= ? AND text \= ?)
keith.commands.remind.statements.setReminder=INSERT INTO reminders (GuildID, ChannelID, UserID, Date, Text) VALUES (?, ?, ?, ?, ?)

keith.commands.stats.statements.returnAdmins=SELECT (DiscordID) FROM users WHERE UserLevel > 2
keith.commands.stats.statements.returnServers=SELECT ServerID, FirstSeen FROM servers

keith.manager.candidate.statements.createCandidate=INSERT INTO users (DiscordID) VALUES (?)
keith.manager.candidate.statements.getCandidate=SELECT FirstSeen, UserLevel, CommandCount, Locale FROM users WHERE DiscordID \= ?
keith.manager.candidate.statements.incrementCommandCount=UPDATE users SET CommandCount \= CommandCount + 1 WHERE DiscordID \= ?
keith.manager.candidate.statements.setAccessLevel=UPDATE users SET UserLevel \= ? WHERE DiscordID \= ?

keith.manager.server.statements.createServer=INSERT INTO servers (ServerID) VALUES (?)
keith.manager.server.statements.getServer=SELECT FirstSeen, prefix, banned, PinChannel FROM servers where serverID \= ?
keith.manager.server.statements.setBanned=UPDATE servers SET banned \= ? WHERE ServerID \= ?
keith.manager.server.statements.setPinChannel=UPDATE servers SET PinChannel \= ? WHERE ServerID \= ?
keith.manager.server.statements.setPrefix=UPDATE servers SET prefix \= ? WHERE ServerID \= ?


########################
# RATE LIMITING
########################
# the value of commands a single candidate can have before a command is rejected
keith.rate-limit.timeout=30

########################
# CONCURRENCY
########################

keith.executor.commands.pool-size.min=1
keith.executor.commands.pool-size.max=4

### how many threads we dedicate to handling message events
keith.executor.messages.pool-size.min=1
keith.executor.messages.pool-size.max=2

### how many threads we dedicate to handling reaction events
keith.executor.reactions.pool-size.min=1
keith.executor.reactions.pool-size.max=2

### how many threads are available for scheduling tasks
keith.executor.scheduler.pool-size.core=1

### how many threads are available for serving reminders
keith.executor.reminders.scheduler.pool-size.core=1






